name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Deps
        run: pip install flet
      - name: Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: flet build apk --project "MyAccount" --org "com.sun" --no-input
      - name: Export
        uses: actions/upload-artifact@v4
        with:
          name: my-final-apk
          path: build/apk/*.apk
